### ISSUE TITLE
Loosen Requirements

### ISSUE THREAD

**Issue by joetheone** [microsoft/Simplify-Docx#10]
Hello,

Is it possible to loosen the requirements for this library. Right now we have:

    install_requires=[
            "lxml==4.3.3",
            "more-itertools==7.0.0",
            "python-docx==0.8.10",
            "six==1.12.0",
            "wincertstore==0.2",
        ],

Could we do something like:

    install_requires=[
            "lxml>=4.3.3,<5",
            "more-itertools==7.0.0",
            "python-docx==0.8.10",
            "six>=1.12.0<2",
            "wincertstore==0.2",
        ],

**Comment by jdthorpe** [comment]
Great suggestion. Updated just now.

**Comment by joetheone** [comment]
Great! Will you release a new minor version of the library then?
