### ISSUE TITLE
Release a new PyPI version

### ISSUE THREAD

**Issue by johnthagen** [microsoft/Simplify-Docx#19]
Could a new release be pushed to PyPI with #18 #13 included?

**Comment by jdthorpe** [comment]
I'll try and push an update this weekend.  (This project is not maintained by the MS Office team, and I maintain this in my "free" time...)

**Comment by jdthorpe** [comment]
Time got away from me over the weekend.  In the meantime, there's always

```sh
pip install git+git://github.com/microsoft/Simplify-Docx.git
```

or 

```sh
pip install git+git://github.com/microsoft/Simplify-Docx.git@a0ac6e79a3c8afb2cfc57bb185ad71b5e80098b1
```

**Comment by johnthagen** [comment]
@jdthorpe Thanks! Yes we've been using the `git+` method in the meantime.

**Comment by a-toms** [comment]
Please would you push the new version? Currently, we need to fork the repo just to change the `docx-python` requirement in the package from `==0.8.10` to `>=0.8.10`.

**Comment by jdthorpe** [comment]
Pushed just now.

**Comment by johnthagen** [comment]
Thanks!

- https://pypi.org/project/simplify-docx/0.1.2/
